<?php

define("SESSION_EXPIRE_TIME", 60 * 60); // in seconds
define("CUSTOMER_EMAIL_VERIFICATION_REQUEST_MAXIMUM_ATTEMPTS", 3);
define("CUSTOMER_EMAIL_VERIFICATION_REQUEST_TIMEOUT", 30); // in seconds

define("ANNOUNCEMENT_INVISIBLE_FROM_CREATION_UPTO", 5); // in minutes